# Generated by Django 5.0.4 on 2024-04-07 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplace',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='food.category'),
        ),
    ]
