# Generated by Django 5.0.4 on 2024-04-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_stars_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcomment',
            name='date',
        ),
        migrations.AddField(
            model_name='foodcomment',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
