# Generated by Django 5.0.4 on 2024-04-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_food_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='id',
            new_name='food_id',
        ),
    ]
