# Generated by Django 5.0.4 on 2024-04-07 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_id_food_food_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcomment',
            name='foodplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.foodplace'),
            preserve_default=False,
        ),
    ]
