# Generated by Django 5.0.4 on 2024-04-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_foodcomment_foodplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcomment',
            name='food',
        ),
    ]
