# Generated by Django 5.0.4 on 2024-04-08 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_foodcomment_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplace',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_food_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
